# coding: utf-8

"""
    Opisanie API Voprosov i Otzyvov

    `Vahno!` Dopuskaetsa 1 zapros v sekundu na metody voprosov i otzyvov v celom. Pri prevyhenii limita do 3 zaprosov v sekundu posleduet blokirovka na 60 sekund.   # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse2009Data(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'subject_id': 'int',
        'subject_name': 'str'
    }

    attribute_map = {
        'subject_id': 'subjectId',
        'subject_name': 'subjectName'
    }

    def __init__(self, subject_id=None, subject_name=None):  # noqa: E501
        """InlineResponse2009Data - a model defined in Swagger"""  # noqa: E501
        self._subject_id = None
        self._subject_name = None
        self.discriminator = None
        if subject_id is not None:
            self.subject_id = subject_id
        if subject_name is not None:
            self.subject_name = subject_name

    @property
    def subject_id(self):
        """Gets the subject_id of this InlineResponse2009Data.  # noqa: E501

        Id kategorii tovara  # noqa: E501

        :return: The subject_id of this InlineResponse2009Data.  # noqa: E501
        :rtype: int
        """
        return self._subject_id

    @subject_id.setter
    def subject_id(self, subject_id):
        """Sets the subject_id of this InlineResponse2009Data.

        Id kategorii tovara  # noqa: E501

        :param subject_id: The subject_id of this InlineResponse2009Data.  # noqa: E501
        :type: int
        """

        self._subject_id = subject_id

    @property
    def subject_name(self):
        """Gets the subject_name of this InlineResponse2009Data.  # noqa: E501

        Nazvanie kategorii tovara  # noqa: E501

        :return: The subject_name of this InlineResponse2009Data.  # noqa: E501
        :rtype: str
        """
        return self._subject_name

    @subject_name.setter
    def subject_name(self, subject_name):
        """Sets the subject_name of this InlineResponse2009Data.

        Nazvanie kategorii tovara  # noqa: E501

        :param subject_name: The subject_name of this InlineResponse2009Data.  # noqa: E501
        :type: str
        """

        self._subject_name = subject_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse2009Data, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse2009Data):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
