# coding: utf-8

"""
    Opisanie API Voprosov i Otzyvov

    `Vahno!` Dopuskaetsa 1 zapros v sekundu na metody voprosov i otzyvov v celom. Pri prevyhenii limita do 3 zaprosov v sekundu posleduet blokirovka na 60 sekund.   # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse2003DataQuestions(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'text': 'str',
        'created_date': 'datetime',
        'state': 'str',
        'answer': 'InlineResponse2003DataAnswer',
        'product_details': 'InlineResponse2003DataProductDetails',
        'was_viewed': 'bool'
    }

    attribute_map = {
        'id': 'id',
        'text': 'text',
        'created_date': 'createdDate',
        'state': 'state',
        'answer': 'answer',
        'product_details': 'productDetails',
        'was_viewed': 'wasViewed'
    }

    def __init__(self, id=None, text=None, created_date=None, state=None, answer=None, product_details=None, was_viewed=None):  # noqa: E501
        """InlineResponse2003DataQuestions - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._text = None
        self._created_date = None
        self._state = None
        self._answer = None
        self._product_details = None
        self._was_viewed = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if text is not None:
            self.text = text
        if created_date is not None:
            self.created_date = created_date
        if state is not None:
            self.state = state
        if answer is not None:
            self.answer = answer
        if product_details is not None:
            self.product_details = product_details
        if was_viewed is not None:
            self.was_viewed = was_viewed

    @property
    def id(self):
        """Gets the id of this InlineResponse2003DataQuestions.  # noqa: E501

        id voprosa  # noqa: E501

        :return: The id of this InlineResponse2003DataQuestions.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this InlineResponse2003DataQuestions.

        id voprosa  # noqa: E501

        :param id: The id of this InlineResponse2003DataQuestions.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def text(self):
        """Gets the text of this InlineResponse2003DataQuestions.  # noqa: E501

        Tekst voprosa  # noqa: E501

        :return: The text of this InlineResponse2003DataQuestions.  # noqa: E501
        :rtype: str
        """
        return self._text

    @text.setter
    def text(self, text):
        """Sets the text of this InlineResponse2003DataQuestions.

        Tekst voprosa  # noqa: E501

        :param text: The text of this InlineResponse2003DataQuestions.  # noqa: E501
        :type: str
        """

        self._text = text

    @property
    def created_date(self):
        """Gets the created_date of this InlineResponse2003DataQuestions.  # noqa: E501

        Data i vrema sozdania voprosa  # noqa: E501

        :return: The created_date of this InlineResponse2003DataQuestions.  # noqa: E501
        :rtype: datetime
        """
        return self._created_date

    @created_date.setter
    def created_date(self, created_date):
        """Sets the created_date of this InlineResponse2003DataQuestions.

        Data i vrema sozdania voprosa  # noqa: E501

        :param created_date: The created_date of this InlineResponse2003DataQuestions.  # noqa: E501
        :type: datetime
        """

        self._created_date = created_date

    @property
    def state(self):
        """Gets the state of this InlineResponse2003DataQuestions.  # noqa: E501

        <dt>Status voprosa:</dt> <dd>`none` - vopros otklonen prodavcom (takoi vopros ne otobrahaetsa na portale pokupatelei)</dd> <dd>`wbRu` - otvet predostavlen, vopros otobrahaetsa na saite pokupatelei</dd> <dd>`suppliersPortalSynch` - novyi vopros</dd>   # noqa: E501

        :return: The state of this InlineResponse2003DataQuestions.  # noqa: E501
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state):
        """Sets the state of this InlineResponse2003DataQuestions.

        <dt>Status voprosa:</dt> <dd>`none` - vopros otklonen prodavcom (takoi vopros ne otobrahaetsa na portale pokupatelei)</dd> <dd>`wbRu` - otvet predostavlen, vopros otobrahaetsa na saite pokupatelei</dd> <dd>`suppliersPortalSynch` - novyi vopros</dd>   # noqa: E501

        :param state: The state of this InlineResponse2003DataQuestions.  # noqa: E501
        :type: str
        """

        self._state = state

    @property
    def answer(self):
        """Gets the answer of this InlineResponse2003DataQuestions.  # noqa: E501


        :return: The answer of this InlineResponse2003DataQuestions.  # noqa: E501
        :rtype: InlineResponse2003DataAnswer
        """
        return self._answer

    @answer.setter
    def answer(self, answer):
        """Sets the answer of this InlineResponse2003DataQuestions.


        :param answer: The answer of this InlineResponse2003DataQuestions.  # noqa: E501
        :type: InlineResponse2003DataAnswer
        """

        self._answer = answer

    @property
    def product_details(self):
        """Gets the product_details of this InlineResponse2003DataQuestions.  # noqa: E501


        :return: The product_details of this InlineResponse2003DataQuestions.  # noqa: E501
        :rtype: InlineResponse2003DataProductDetails
        """
        return self._product_details

    @product_details.setter
    def product_details(self, product_details):
        """Sets the product_details of this InlineResponse2003DataQuestions.


        :param product_details: The product_details of this InlineResponse2003DataQuestions.  # noqa: E501
        :type: InlineResponse2003DataProductDetails
        """

        self._product_details = product_details

    @property
    def was_viewed(self):
        """Gets the was_viewed of this InlineResponse2003DataQuestions.  # noqa: E501

        Prosmotren li vopros  # noqa: E501

        :return: The was_viewed of this InlineResponse2003DataQuestions.  # noqa: E501
        :rtype: bool
        """
        return self._was_viewed

    @was_viewed.setter
    def was_viewed(self, was_viewed):
        """Sets the was_viewed of this InlineResponse2003DataQuestions.

        Prosmotren li vopros  # noqa: E501

        :param was_viewed: The was_viewed of this InlineResponse2003DataQuestions.  # noqa: E501
        :type: bool
        """

        self._was_viewed = was_viewed

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse2003DataQuestions, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse2003DataQuestions):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
