# coding: utf-8

"""
    Opisanie API Voprosov i Otzyvov

    `Vahno!` Dopuskaetsa 1 zapros v sekundu na metody voprosov i otzyvov v celom. Pri prevyhenii limita do 3 zaprosov v sekundu posleduet blokirovka na 60 sekund.   # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ProductRating(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'nm_id': 'int',
        'imt_id': 'int',
        'valuations_sum': 'int',
        'feedbacks_count': 'int',
        'valuation': 'float',
        'product_name': 'str',
        'supplier_article': 'str',
        'brand_name': 'str'
    }

    attribute_map = {
        'nm_id': 'nmId',
        'imt_id': 'imtId',
        'valuations_sum': 'valuationsSum',
        'feedbacks_count': 'feedbacksCount',
        'valuation': 'valuation',
        'product_name': 'productName',
        'supplier_article': 'supplierArticle',
        'brand_name': 'brandName'
    }

    def __init__(self, nm_id=None, imt_id=None, valuations_sum=None, feedbacks_count=None, valuation=None, product_name=None, supplier_article=None, brand_name=None):  # noqa: E501
        """ProductRating - a model defined in Swagger"""  # noqa: E501
        self._nm_id = None
        self._imt_id = None
        self._valuations_sum = None
        self._feedbacks_count = None
        self._valuation = None
        self._product_name = None
        self._supplier_article = None
        self._brand_name = None
        self.discriminator = None
        if nm_id is not None:
            self.nm_id = nm_id
        if imt_id is not None:
            self.imt_id = imt_id
        if valuations_sum is not None:
            self.valuations_sum = valuations_sum
        if feedbacks_count is not None:
            self.feedbacks_count = feedbacks_count
        if valuation is not None:
            self.valuation = valuation
        if product_name is not None:
            self.product_name = product_name
        if supplier_article is not None:
            self.supplier_article = supplier_article
        if brand_name is not None:
            self.brand_name = brand_name

    @property
    def nm_id(self):
        """Gets the nm_id of this ProductRating.  # noqa: E501

        Artikul WB  # noqa: E501

        :return: The nm_id of this ProductRating.  # noqa: E501
        :rtype: int
        """
        return self._nm_id

    @nm_id.setter
    def nm_id(self, nm_id):
        """Sets the nm_id of this ProductRating.

        Artikul WB  # noqa: E501

        :param nm_id: The nm_id of this ProductRating.  # noqa: E501
        :type: int
        """

        self._nm_id = nm_id

    @property
    def imt_id(self):
        """Gets the imt_id of this ProductRating.  # noqa: E501

        Identifikator kartohki tovara  # noqa: E501

        :return: The imt_id of this ProductRating.  # noqa: E501
        :rtype: int
        """
        return self._imt_id

    @imt_id.setter
    def imt_id(self, imt_id):
        """Sets the imt_id of this ProductRating.

        Identifikator kartohki tovara  # noqa: E501

        :param imt_id: The imt_id of this ProductRating.  # noqa: E501
        :type: int
        """

        self._imt_id = imt_id

    @property
    def valuations_sum(self):
        """Gets the valuations_sum of this ProductRating.  # noqa: E501

        Summa ocenok  # noqa: E501

        :return: The valuations_sum of this ProductRating.  # noqa: E501
        :rtype: int
        """
        return self._valuations_sum

    @valuations_sum.setter
    def valuations_sum(self, valuations_sum):
        """Sets the valuations_sum of this ProductRating.

        Summa ocenok  # noqa: E501

        :param valuations_sum: The valuations_sum of this ProductRating.  # noqa: E501
        :type: int
        """

        self._valuations_sum = valuations_sum

    @property
    def feedbacks_count(self):
        """Gets the feedbacks_count of this ProductRating.  # noqa: E501

        Kolihestvo otzyvov  # noqa: E501

        :return: The feedbacks_count of this ProductRating.  # noqa: E501
        :rtype: int
        """
        return self._feedbacks_count

    @feedbacks_count.setter
    def feedbacks_count(self, feedbacks_count):
        """Sets the feedbacks_count of this ProductRating.

        Kolihestvo otzyvov  # noqa: E501

        :param feedbacks_count: The feedbacks_count of this ProductRating.  # noqa: E501
        :type: int
        """

        self._feedbacks_count = feedbacks_count

    @property
    def valuation(self):
        """Gets the valuation of this ProductRating.  # noqa: E501

        Srednaa ocenka  # noqa: E501

        :return: The valuation of this ProductRating.  # noqa: E501
        :rtype: float
        """
        return self._valuation

    @valuation.setter
    def valuation(self, valuation):
        """Sets the valuation of this ProductRating.

        Srednaa ocenka  # noqa: E501

        :param valuation: The valuation of this ProductRating.  # noqa: E501
        :type: float
        """

        self._valuation = valuation

    @property
    def product_name(self):
        """Gets the product_name of this ProductRating.  # noqa: E501

        Nazvanie tovara  # noqa: E501

        :return: The product_name of this ProductRating.  # noqa: E501
        :rtype: str
        """
        return self._product_name

    @product_name.setter
    def product_name(self, product_name):
        """Sets the product_name of this ProductRating.

        Nazvanie tovara  # noqa: E501

        :param product_name: The product_name of this ProductRating.  # noqa: E501
        :type: str
        """

        self._product_name = product_name

    @property
    def supplier_article(self):
        """Gets the supplier_article of this ProductRating.  # noqa: E501

        Artikul prodavca  # noqa: E501

        :return: The supplier_article of this ProductRating.  # noqa: E501
        :rtype: str
        """
        return self._supplier_article

    @supplier_article.setter
    def supplier_article(self, supplier_article):
        """Sets the supplier_article of this ProductRating.

        Artikul prodavca  # noqa: E501

        :param supplier_article: The supplier_article of this ProductRating.  # noqa: E501
        :type: str
        """

        self._supplier_article = supplier_article

    @property
    def brand_name(self):
        """Gets the brand_name of this ProductRating.  # noqa: E501

        Brend tovara  # noqa: E501

        :return: The brand_name of this ProductRating.  # noqa: E501
        :rtype: str
        """
        return self._brand_name

    @brand_name.setter
    def brand_name(self, brand_name):
        """Sets the brand_name of this ProductRating.

        Brend tovara  # noqa: E501

        :param brand_name: The brand_name of this ProductRating.  # noqa: E501
        :type: str
        """

        self._brand_name = brand_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ProductRating, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProductRating):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
