# coding: utf-8

"""
    Opisanie API Marketplace

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.18
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class WarehousesWarehouseIdBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'office_id': 'int'
    }

    attribute_map = {
        'name': 'name',
        'office_id': 'officeId'
    }

    def __init__(self, name=None, office_id=None):  # noqa: E501
        """WarehousesWarehouseIdBody - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._office_id = None
        self.discriminator = None
        self.name = name
        self.office_id = office_id

    @property
    def name(self):
        """Gets the name of this WarehousesWarehouseIdBody.  # noqa: E501

        Ima sklada prodavca  # noqa: E501

        :return: The name of this WarehousesWarehouseIdBody.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this WarehousesWarehouseIdBody.

        Ima sklada prodavca  # noqa: E501

        :param name: The name of this WarehousesWarehouseIdBody.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def office_id(self):
        """Gets the office_id of this WarehousesWarehouseIdBody.  # noqa: E501

        Identifikator sklada WB  # noqa: E501

        :return: The office_id of this WarehousesWarehouseIdBody.  # noqa: E501
        :rtype: int
        """
        return self._office_id

    @office_id.setter
    def office_id(self, office_id):
        """Sets the office_id of this WarehousesWarehouseIdBody.

        Identifikator sklada WB  # noqa: E501

        :param office_id: The office_id of this WarehousesWarehouseIdBody.  # noqa: E501
        :type: int
        """
        if office_id is None:
            raise ValueError("Invalid value for `office_id`, must not be `None`")  # noqa: E501

        self._office_id = office_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(WarehousesWarehouseIdBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, WarehousesWarehouseIdBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
