from __future__ import absolute_import

# flake8: noqa

# import apis into api package
from wildberries_api_client.promotion.api.aktivnost_kampanii_api import AktivnostKampaniiApi
from wildberries_api_client.promotion.api.aktivnost_mediakampanii_api import AktivnostMediakampaniiApi
from wildberries_api_client.promotion.api.finansy_api import FinansyApi
from wildberries_api_client.promotion.api.media_api import MediaApi
from wildberries_api_client.promotion.api.prodvihenie_api import ProdvihenieApi
from wildberries_api_client.promotion.api.slovari_api import SlovariApi
from wildberries_api_client.promotion.api.statistika_api import StatistikaApi
from wildberries_api_client.promotion.api.statistika_mediakampanii_api import StatistikaMediakampaniiApi
from wildberries_api_client.promotion.api.stavki_api import StavkiApi
from wildberries_api_client.promotion.api.stavki_mediakampanii_api import StavkiMediakampaniiApi
from wildberries_api_client.promotion.api.upravlenie_obhimi_parametrami_kampanii_api import UpravlenieObhimiParametramiKampaniiApi
from wildberries_api_client.promotion.api.upravlenie_parametrami_avtomatiheskih_kampanii_api import UpravlenieParametramiAvtomatiheskihKampaniiApi
from wildberries_api_client.promotion.api.upravlenie_parametrami_kampanii_v_poiske_api import UpravlenieParametramiKampaniiVPoiskeApi
