# coding: utf-8

"""
    Opisanie API Statistiki

    S pomohu etih metodov mohno poluhit othety.   # noqa: E501

    OpenAPI spec version: 2.18
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class GetTasksResponseBytesErrorDataTasks(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'last_proc_err': 'str',
        'status': 'str'
    }

    attribute_map = {
        'id': 'id',
        'last_proc_err': 'last_proc_err',
        'status': 'status'
    }

    def __init__(self, id=None, last_proc_err=None, status=None):  # noqa: E501
        """GetTasksResponseBytesErrorDataTasks - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._last_proc_err = None
        self._status = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if last_proc_err is not None:
            self.last_proc_err = last_proc_err
        if status is not None:
            self.status = status

    @property
    def id(self):
        """Gets the id of this GetTasksResponseBytesErrorDataTasks.  # noqa: E501


        :return: The id of this GetTasksResponseBytesErrorDataTasks.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this GetTasksResponseBytesErrorDataTasks.


        :param id: The id of this GetTasksResponseBytesErrorDataTasks.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def last_proc_err(self):
        """Gets the last_proc_err of this GetTasksResponseBytesErrorDataTasks.  # noqa: E501


        :return: The last_proc_err of this GetTasksResponseBytesErrorDataTasks.  # noqa: E501
        :rtype: str
        """
        return self._last_proc_err

    @last_proc_err.setter
    def last_proc_err(self, last_proc_err):
        """Sets the last_proc_err of this GetTasksResponseBytesErrorDataTasks.


        :param last_proc_err: The last_proc_err of this GetTasksResponseBytesErrorDataTasks.  # noqa: E501
        :type: str
        """

        self._last_proc_err = last_proc_err

    @property
    def status(self):
        """Gets the status of this GetTasksResponseBytesErrorDataTasks.  # noqa: E501


        :return: The status of this GetTasksResponseBytesErrorDataTasks.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this GetTasksResponseBytesErrorDataTasks.


        :param status: The status of this GetTasksResponseBytesErrorDataTasks.  # noqa: E501
        :type: str
        """

        self._status = status

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GetTasksResponseBytesErrorDataTasks, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GetTasksResponseBytesErrorDataTasks):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
