# coding: utf-8

"""
    Opisanie API Prodvihenie

    Sinhronizacia dannyh iz bd proishodit raz v 3 minuty.  <br>Izmenenie statusa proishodit raz v 1 minutu. Vnutri etogo intervala budet sohraneno poslednee deistvie po izmeneniu statusa. <br>Izmenenie stavki proishodit raz v 30 sekund. Vnutri etogo intervala budet sohraneno poslednee deistvie po izmeneniu stavki.   # noqa: E501

    OpenAPI spec version: 2.20
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse20022(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'words': 'InlineResponse20022Words',
        'stat': 'list[InlineResponse20022Stat]'
    }

    attribute_map = {
        'words': 'words',
        'stat': 'stat'
    }

    def __init__(self, words=None, stat=None):  # noqa: E501
        """InlineResponse20022 - a model defined in Swagger"""  # noqa: E501
        self._words = None
        self._stat = None
        self.discriminator = None
        if words is not None:
            self.words = words
        if stat is not None:
            self.stat = stat

    @property
    def words(self):
        """Gets the words of this InlineResponse20022.  # noqa: E501


        :return: The words of this InlineResponse20022.  # noqa: E501
        :rtype: InlineResponse20022Words
        """
        return self._words

    @words.setter
    def words(self, words):
        """Sets the words of this InlineResponse20022.


        :param words: The words of this InlineResponse20022.  # noqa: E501
        :type: InlineResponse20022Words
        """

        self._words = words

    @property
    def stat(self):
        """Gets the stat of this InlineResponse20022.  # noqa: E501

        Massiv informacii po statistike.<br> <b>Pervyi element massiva</b> s `keyword: \"Vsego po kampanii\"` soderhit summarnuu informaciu po vsem kluhevym frazam.<br> <b>Kahdyi sleduuhii element massiva</b> soderhit informaciu po otdelnoi kluhevoi fraze.<br> Otobrahaetsa 60 kluhevyh fraz s naibolhim kolihestvom prosmotrov.   # noqa: E501

        :return: The stat of this InlineResponse20022.  # noqa: E501
        :rtype: list[InlineResponse20022Stat]
        """
        return self._stat

    @stat.setter
    def stat(self, stat):
        """Sets the stat of this InlineResponse20022.

        Massiv informacii po statistike.<br> <b>Pervyi element massiva</b> s `keyword: \"Vsego po kampanii\"` soderhit summarnuu informaciu po vsem kluhevym frazam.<br> <b>Kahdyi sleduuhii element massiva</b> soderhit informaciu po otdelnoi kluhevoi fraze.<br> Otobrahaetsa 60 kluhevyh fraz s naibolhim kolihestvom prosmotrov.   # noqa: E501

        :param stat: The stat of this InlineResponse20022.  # noqa: E501
        :type: list[InlineResponse20022Stat]
        """

        self._stat = stat

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse20022, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse20022):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
