# coding: utf-8

"""
    Opisanie API Prodvihenie

    Sinhronizacia dannyh iz bd proishodit raz v 3 minuty.  <br>Izmenenie statusa proishodit raz v 1 minutu. Vnutri etogo intervala budet sohraneno poslednee deistvie po izmeneniu statusa. <br>Izmenenie stavki proishodit raz v 30 sekund. Vnutri etogo intervala budet sohraneno poslednee deistvie po izmeneniu stavki.   # noqa: E501

    OpenAPI spec version: 2.20
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse20025Catalog(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'views': 'int',
        'clicks': 'int',
        'orders': 'int',
        'sum': 'int'
    }

    attribute_map = {
        'views': 'views',
        'clicks': 'clicks',
        'orders': 'orders',
        'sum': 'sum'
    }

    def __init__(self, views=None, clicks=None, orders=None, sum=None):  # noqa: E501
        """InlineResponse20025Catalog - a model defined in Swagger"""  # noqa: E501
        self._views = None
        self._clicks = None
        self._orders = None
        self._sum = None
        self.discriminator = None
        if views is not None:
            self.views = views
        if clicks is not None:
            self.clicks = clicks
        if orders is not None:
            self.orders = orders
        if sum is not None:
            self.sum = sum

    @property
    def views(self):
        """Gets the views of this InlineResponse20025Catalog.  # noqa: E501

        Kolihestvo prosmotrov  # noqa: E501

        :return: The views of this InlineResponse20025Catalog.  # noqa: E501
        :rtype: int
        """
        return self._views

    @views.setter
    def views(self, views):
        """Sets the views of this InlineResponse20025Catalog.

        Kolihestvo prosmotrov  # noqa: E501

        :param views: The views of this InlineResponse20025Catalog.  # noqa: E501
        :type: int
        """

        self._views = views

    @property
    def clicks(self):
        """Gets the clicks of this InlineResponse20025Catalog.  # noqa: E501

        Kolihestvo klikov  # noqa: E501

        :return: The clicks of this InlineResponse20025Catalog.  # noqa: E501
        :rtype: int
        """
        return self._clicks

    @clicks.setter
    def clicks(self, clicks):
        """Sets the clicks of this InlineResponse20025Catalog.

        Kolihestvo klikov  # noqa: E501

        :param clicks: The clicks of this InlineResponse20025Catalog.  # noqa: E501
        :type: int
        """

        self._clicks = clicks

    @property
    def orders(self):
        """Gets the orders of this InlineResponse20025Catalog.  # noqa: E501

        Kolihestvo zakazov  # noqa: E501

        :return: The orders of this InlineResponse20025Catalog.  # noqa: E501
        :rtype: int
        """
        return self._orders

    @orders.setter
    def orders(self, orders):
        """Sets the orders of this InlineResponse20025Catalog.

        Kolihestvo zakazov  # noqa: E501

        :param orders: The orders of this InlineResponse20025Catalog.  # noqa: E501
        :type: int
        """

        self._orders = orders

    @property
    def sum(self):
        """Gets the sum of this InlineResponse20025Catalog.  # noqa: E501

        Zatraty, ₽.  # noqa: E501

        :return: The sum of this InlineResponse20025Catalog.  # noqa: E501
        :rtype: int
        """
        return self._sum

    @sum.setter
    def sum(self, sum):
        """Sets the sum of this InlineResponse20025Catalog.

        Zatraty, ₽.  # noqa: E501

        :param sum: The sum of this InlineResponse20025Catalog.  # noqa: E501
        :type: int
        """

        self._sum = sum

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse20025Catalog, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse20025Catalog):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
