# coding: utf-8

"""
    Opisanie API Prodvihenie

    Sinhronizacia dannyh iz bd proishodit raz v 3 minuty.  <br>Izmenenie statusa proishodit raz v 1 minutu. Vnutri etogo intervala budet sohraneno poslednee deistvie po izmeneniu statusa. <br>Izmenenie stavki proishodit raz v 30 sekund. Vnutri etogo intervala budet sohraneno poslednee deistvie po izmeneniu stavki.   # noqa: E501

    OpenAPI spec version: 2.20
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ResponseWithDateInner(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'dates': 'list[date]',
        'views': 'int',
        'clicks': 'int',
        'ctr': 'float',
        'cpc': 'float',
        'sum': 'float',
        'atbs': 'int',
        'orders': 'int',
        'cr': 'int',
        'shks': 'int',
        'sum_price': 'float',
        'days': 'Days',
        'booster_stats': 'BoosterStats',
        'advert_id': 'int'
    }

    attribute_map = {
        'dates': 'dates',
        'views': 'views',
        'clicks': 'clicks',
        'ctr': 'ctr',
        'cpc': 'cpc',
        'sum': 'sum',
        'atbs': 'atbs',
        'orders': 'orders',
        'cr': 'cr',
        'shks': 'shks',
        'sum_price': 'sum_price',
        'days': 'days',
        'booster_stats': 'boosterStats',
        'advert_id': 'advertId'
    }

    def __init__(self, dates=None, views=None, clicks=None, ctr=None, cpc=None, sum=None, atbs=None, orders=None, cr=None, shks=None, sum_price=None, days=None, booster_stats=None, advert_id=None):  # noqa: E501
        """ResponseWithDateInner - a model defined in Swagger"""  # noqa: E501
        self._dates = None
        self._views = None
        self._clicks = None
        self._ctr = None
        self._cpc = None
        self._sum = None
        self._atbs = None
        self._orders = None
        self._cr = None
        self._shks = None
        self._sum_price = None
        self._days = None
        self._booster_stats = None
        self._advert_id = None
        self.discriminator = None
        if dates is not None:
            self.dates = dates
        if views is not None:
            self.views = views
        if clicks is not None:
            self.clicks = clicks
        if ctr is not None:
            self.ctr = ctr
        if cpc is not None:
            self.cpc = cpc
        if sum is not None:
            self.sum = sum
        if atbs is not None:
            self.atbs = atbs
        if orders is not None:
            self.orders = orders
        if cr is not None:
            self.cr = cr
        if shks is not None:
            self.shks = shks
        if sum_price is not None:
            self.sum_price = sum_price
        if days is not None:
            self.days = days
        if booster_stats is not None:
            self.booster_stats = booster_stats
        if advert_id is not None:
            self.advert_id = advert_id

    @property
    def dates(self):
        """Gets the dates of this ResponseWithDateInner.  # noqa: E501

        Daty, za kotorye neobhodimo vydat informaciu.  # noqa: E501

        :return: The dates of this ResponseWithDateInner.  # noqa: E501
        :rtype: list[date]
        """
        return self._dates

    @dates.setter
    def dates(self, dates):
        """Sets the dates of this ResponseWithDateInner.

        Daty, za kotorye neobhodimo vydat informaciu.  # noqa: E501

        :param dates: The dates of this ResponseWithDateInner.  # noqa: E501
        :type: list[date]
        """

        self._dates = dates

    @property
    def views(self):
        """Gets the views of this ResponseWithDateInner.  # noqa: E501

        Kolihestvo prosmotrov. <br> Za vse dni, po vsem artikulam WB i platformam.   # noqa: E501

        :return: The views of this ResponseWithDateInner.  # noqa: E501
        :rtype: int
        """
        return self._views

    @views.setter
    def views(self, views):
        """Sets the views of this ResponseWithDateInner.

        Kolihestvo prosmotrov. <br> Za vse dni, po vsem artikulam WB i platformam.   # noqa: E501

        :param views: The views of this ResponseWithDateInner.  # noqa: E501
        :type: int
        """

        self._views = views

    @property
    def clicks(self):
        """Gets the clicks of this ResponseWithDateInner.  # noqa: E501

        Kolihestvo klikov.<br> Za vse dni, po vsem artikulam WB i platformam.   # noqa: E501

        :return: The clicks of this ResponseWithDateInner.  # noqa: E501
        :rtype: int
        """
        return self._clicks

    @clicks.setter
    def clicks(self, clicks):
        """Sets the clicks of this ResponseWithDateInner.

        Kolihestvo klikov.<br> Za vse dni, po vsem artikulam WB i platformam.   # noqa: E501

        :param clicks: The clicks of this ResponseWithDateInner.  # noqa: E501
        :type: int
        """

        self._clicks = clicks

    @property
    def ctr(self):
        """Gets the ctr of this ResponseWithDateInner.  # noqa: E501

        Pokazatel klikabelnosti.<br> Otnohenie hisla klikov k kolihestvu pokazov. Vyrahaetsa v procentah.<br> Za vse dni, po vsem artikulam WB i platformam.<br>   # noqa: E501

        :return: The ctr of this ResponseWithDateInner.  # noqa: E501
        :rtype: float
        """
        return self._ctr

    @ctr.setter
    def ctr(self, ctr):
        """Sets the ctr of this ResponseWithDateInner.

        Pokazatel klikabelnosti.<br> Otnohenie hisla klikov k kolihestvu pokazov. Vyrahaetsa v procentah.<br> Za vse dni, po vsem artikulam WB i platformam.<br>   # noqa: E501

        :param ctr: The ctr of this ResponseWithDateInner.  # noqa: E501
        :type: float
        """

        self._ctr = ctr

    @property
    def cpc(self):
        """Gets the cpc of this ResponseWithDateInner.  # noqa: E501

        Srednaa stoimost klika, ₽.<br> Za vse dni, po vsem artikulam WB i platformam.   # noqa: E501

        :return: The cpc of this ResponseWithDateInner.  # noqa: E501
        :rtype: float
        """
        return self._cpc

    @cpc.setter
    def cpc(self, cpc):
        """Sets the cpc of this ResponseWithDateInner.

        Srednaa stoimost klika, ₽.<br> Za vse dni, po vsem artikulam WB i platformam.   # noqa: E501

        :param cpc: The cpc of this ResponseWithDateInner.  # noqa: E501
        :type: float
        """

        self._cpc = cpc

    @property
    def sum(self):
        """Gets the sum of this ResponseWithDateInner.  # noqa: E501

        Zatraty, ₽.<br> Za vse dni, po vsem artikulam WB i platformam.   # noqa: E501

        :return: The sum of this ResponseWithDateInner.  # noqa: E501
        :rtype: float
        """
        return self._sum

    @sum.setter
    def sum(self, sum):
        """Sets the sum of this ResponseWithDateInner.

        Zatraty, ₽.<br> Za vse dni, po vsem artikulam WB i platformam.   # noqa: E501

        :param sum: The sum of this ResponseWithDateInner.  # noqa: E501
        :type: float
        """

        self._sum = sum

    @property
    def atbs(self):
        """Gets the atbs of this ResponseWithDateInner.  # noqa: E501

        Kolihestvo dobavlenii tovarov v korzinu.<br> Za vse dni, po vsem artikulam WB i platformam.   # noqa: E501

        :return: The atbs of this ResponseWithDateInner.  # noqa: E501
        :rtype: int
        """
        return self._atbs

    @atbs.setter
    def atbs(self, atbs):
        """Sets the atbs of this ResponseWithDateInner.

        Kolihestvo dobavlenii tovarov v korzinu.<br> Za vse dni, po vsem artikulam WB i platformam.   # noqa: E501

        :param atbs: The atbs of this ResponseWithDateInner.  # noqa: E501
        :type: int
        """

        self._atbs = atbs

    @property
    def orders(self):
        """Gets the orders of this ResponseWithDateInner.  # noqa: E501

        Kolihestvo zakazov.<br> Za vse dni, po vsem artikulam WB i platformam.   # noqa: E501

        :return: The orders of this ResponseWithDateInner.  # noqa: E501
        :rtype: int
        """
        return self._orders

    @orders.setter
    def orders(self, orders):
        """Sets the orders of this ResponseWithDateInner.

        Kolihestvo zakazov.<br> Za vse dni, po vsem artikulam WB i platformam.   # noqa: E501

        :param orders: The orders of this ResponseWithDateInner.  # noqa: E501
        :type: int
        """

        self._orders = orders

    @property
    def cr(self):
        """Gets the cr of this ResponseWithDateInner.  # noqa: E501

        CR(conversion rate) — eto otnohenie kolihestva zakazov k obhemu kolihestvu posehenii kampanii.<br> Za vse dni, po vsem artikulam WB i platformam.   # noqa: E501

        :return: The cr of this ResponseWithDateInner.  # noqa: E501
        :rtype: int
        """
        return self._cr

    @cr.setter
    def cr(self, cr):
        """Sets the cr of this ResponseWithDateInner.

        CR(conversion rate) — eto otnohenie kolihestva zakazov k obhemu kolihestvu posehenii kampanii.<br> Za vse dni, po vsem artikulam WB i platformam.   # noqa: E501

        :param cr: The cr of this ResponseWithDateInner.  # noqa: E501
        :type: int
        """

        self._cr = cr

    @property
    def shks(self):
        """Gets the shks of this ResponseWithDateInner.  # noqa: E501

        Kolihestvo zakazannyh tovarov, ht.<br> Za vse dni, po vsem artikulam WB i platformam.   # noqa: E501

        :return: The shks of this ResponseWithDateInner.  # noqa: E501
        :rtype: int
        """
        return self._shks

    @shks.setter
    def shks(self, shks):
        """Sets the shks of this ResponseWithDateInner.

        Kolihestvo zakazannyh tovarov, ht.<br> Za vse dni, po vsem artikulam WB i platformam.   # noqa: E501

        :param shks: The shks of this ResponseWithDateInner.  # noqa: E501
        :type: int
        """

        self._shks = shks

    @property
    def sum_price(self):
        """Gets the sum_price of this ResponseWithDateInner.  # noqa: E501

        Zakazov na summu, ₽<br> Za vse dni, po vsem artikulam WB i platformam.   # noqa: E501

        :return: The sum_price of this ResponseWithDateInner.  # noqa: E501
        :rtype: float
        """
        return self._sum_price

    @sum_price.setter
    def sum_price(self, sum_price):
        """Sets the sum_price of this ResponseWithDateInner.

        Zakazov na summu, ₽<br> Za vse dni, po vsem artikulam WB i platformam.   # noqa: E501

        :param sum_price: The sum_price of this ResponseWithDateInner.  # noqa: E501
        :type: float
        """

        self._sum_price = sum_price

    @property
    def days(self):
        """Gets the days of this ResponseWithDateInner.  # noqa: E501


        :return: The days of this ResponseWithDateInner.  # noqa: E501
        :rtype: Days
        """
        return self._days

    @days.setter
    def days(self, days):
        """Sets the days of this ResponseWithDateInner.


        :param days: The days of this ResponseWithDateInner.  # noqa: E501
        :type: Days
        """

        self._days = days

    @property
    def booster_stats(self):
        """Gets the booster_stats of this ResponseWithDateInner.  # noqa: E501


        :return: The booster_stats of this ResponseWithDateInner.  # noqa: E501
        :rtype: BoosterStats
        """
        return self._booster_stats

    @booster_stats.setter
    def booster_stats(self, booster_stats):
        """Sets the booster_stats of this ResponseWithDateInner.


        :param booster_stats: The booster_stats of this ResponseWithDateInner.  # noqa: E501
        :type: BoosterStats
        """

        self._booster_stats = booster_stats

    @property
    def advert_id(self):
        """Gets the advert_id of this ResponseWithDateInner.  # noqa: E501

        ID kampanii  # noqa: E501

        :return: The advert_id of this ResponseWithDateInner.  # noqa: E501
        :rtype: int
        """
        return self._advert_id

    @advert_id.setter
    def advert_id(self, advert_id):
        """Sets the advert_id of this ResponseWithDateInner.

        ID kampanii  # noqa: E501

        :param advert_id: The advert_id of this ResponseWithDateInner.  # noqa: E501
        :type: int
        """

        self._advert_id = advert_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ResponseWithDateInner, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ResponseWithDateInner):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
